// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ZeynalabdiddyRuhuGelmis.DAL.Contexts;

#nullable disable

namespace ZeynalabdiddyRuhuGelmis.DAL.Migrations
{
    [DbContext(typeof(IdiotNiggerDBContext))]
    [Migration("20250526143711_initial")]
    partial class initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ZeynalabdiddyRuhuGelmis.DAL.Models.NiggaThatNeedHelp", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("About")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ForWhat")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Img")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("WeGot")
                        .HasColumnType("float");

                    b.Property<double>("WeNeed")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("niggasThatNeedHelp");
                });
#pragma warning restore 612, 618
        }
    }
}
